### ISSUE TITLE
Form fields on Recruitment page

### ISSUE THREAD

**Issue by kjneaville** [kjneaville/343-Final-Project#4]

**Comment by Lman95** [comment]
Is the school input for university or major?

**Comment by Lman95** [comment]
Also, for year do you guys want freshman, sophomore, etc., expected graduation, or 1st year, 2nd year, etc.?

**Comment by kjneaville** [comment]
School should be actual school since high schoolers may fill it out to who
are planning on coming to uw, you can do grades as High School Senior,
Freshman, Sophomore, Junior

**Comment by Lman95** [comment]
Cool, so only include up to Junior?

**Comment by Lman95** [comment]
Finished name, year, school, phone, and email. Let me know if you want to include achievements or hobbies
