### ISSUE TITLE
Search bar for members (and possibly twitter area)

### ISSUE THREAD

**Issue by kjneaville** [kjneaville/343-Final-Project#8]
Will be very similar to search bar on Dawg Coffee assignment so that people can search the member's area (for a certain high school for example). Should be in top right below the header picture of house.

**Comment by Lman95** [comment]
Added search bar for members. The label pops to the top when on a smaller screen, but it doesn't look too bad. I just can't figure out how to keep it from doing that, but feel free to mess with the styling if you want.
